import os


TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "PUT_YOUR_TELEGRAM_BOT_TOKEN_HERE")

TELEGRAM_ALLOWED_CHAT_ID = os.getenv("TELEGRAM_ALLOWED_CHAT_ID")

TELEGRAM_ALLOWED_THREAD_ID = os.getenv("TELEGRAM_ALLOWED_THREAD_ID")

NOCODB_URL = os.getenv("NOCODB_URL", "http://localhost:8080")

NOCODB_API_TOKEN = os.getenv("NOCODB_API_TOKEN", "PUT_YOUR_NOCODB_TOKEN_HERE")

TABLE_ID = os.getenv("TABLE_ID", "moslcqfantzr0mo")

OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")

AI_MODEL = os.getenv("AI_MODEL", "qwen3:14b")

POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")

POSTGRES_DB = os.getenv("POSTGRES_DB", "automationdb")

POSTGRES_USER = os.getenv("POSTGRES_USER", "admin")

POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "PUT_YOUR_POSTGRES_PASSWORD_HERE")

POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5433")

POSTGRES_CONNECT_TIMEOUT_SECONDS = int(os.getenv("POSTGRES_CONNECT_TIMEOUT_SECONDS", "5"))

POSTGRES_STATEMENT_TIMEOUT_MS = int(os.getenv("POSTGRES_STATEMENT_TIMEOUT_MS", "30000"))

TRANSACTION_SCHEMA = os.getenv("TRANSACTION_SCHEMA", "pipkgfu2wr9qxyy")

TRANSACTION_TABLE = os.getenv("TRANSACTION_TABLE", "Transection")

FARM_TRANSECTION_TABLE = os.getenv("FARM_TRANSECTION_TABLE", "farm_transection")

SOTEPHWAR_TRANSECTION_TABLE = os.getenv("SOTEPHWAR_TRANSECTION_TABLE", "Sotephwar_Transection")

SOTEPHWAR_INVENTORY_TABLE = os.getenv("SOTEPHWAR_INVENTORY_TABLE", "Sotephwar_Inventory")

FINANCIAL_OBLIGATIONS_TABLE = os.getenv("FINANCIAL_OBLIGATIONS_TABLE", "Financial_Obligations")

PAYMENT_RECEIVE_TABLE = os.getenv("PAYMENT_RECEIVE_TABLE", "Payment_Receive")

GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID", "bigshotagribusiness@gmail.com")

GOOGLE_CALENDAR_CREDENTIALS_FILE = os.getenv("GOOGLE_CALENDAR_CREDENTIALS_FILE", "google_calendar_credentials.json")

GOOGLE_CALENDAR_TOKEN_FILE = os.getenv("GOOGLE_CALENDAR_TOKEN_FILE", "google_calendar_token.json")

GOOGLE_CALENDAR_TIMEZONE = os.getenv("GOOGLE_CALENDAR_TIMEZONE", "Asia/Yangon")

# 10080=7 days, 4320=3 days, 1440=1 day before the due date.
GOOGLE_CALENDAR_REMINDER_MINUTES = os.getenv("GOOGLE_CALENDAR_REMINDER_MINUTES", "10080,4320,1440")

LOCAL_UTC_OFFSET_MINUTES = int(os.getenv("LOCAL_UTC_OFFSET_MINUTES", "390"))
