(() => {
  "use strict";
  const state={audit:null,page:1,pages:1,classification:"",decision:"",search:"",sort:"id",direction:"asc",selected:new Set()};
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
  const json=async(url,options={})=>{const response=await fetch(url,options);let body;try{body=await response.json()}catch(_){throw new Error(`Invalid response (${response.status})`)}if(!response.ok||!body.ok)throw new Error(body.error||"Request failed");return body};
  const notice=(message,bad=false)=>{const el=$("daNotice");el.hidden=false;el.className=`da-notice ${bad?"bad":"good"}`;el.textContent=message;window.scrollTo({top:0,behavior:"smooth"})};
  const view=name=>{document.querySelectorAll(".da-view").forEach(el=>el.hidden=true);document.querySelectorAll(".da-workflow button").forEach(button=>button.classList.toggle("active",button.dataset.view===name));const id="da"+name.split("-").map(part=>part[0].toUpperCase()+part.slice(1)).join("");const target=$(id);if(target)target.hidden=false;if(name==="review")loadRows();if(name==="history")loadHistory();if(name.endsWith("alias"))loadAliases(name.startsWith("customer")?"customer":"product")};
  document.querySelectorAll(".da-workflow button").forEach(button=>button.addEventListener("click",()=>view(button.dataset.view)));
  function profile(audit){state.audit=audit;$("daFileProfile").hidden=false;$("daFileProfile").innerHTML=`<h2>File profile</h2><div class="da-profile-grid"><div><span>Filename</span><strong>${esc(audit.filename)}</strong></div><div><span>Sheet</span><strong>${esc(audit.sheet_name)}</strong></div><div><span>Rows</span><strong>${audit.source_rows}</strong></div><div><span>Columns</span><strong>${audit.source_columns}</strong></div><div><span>Detected date</span><strong>${esc(audit.detected_date||"—")}</strong></div><div><span>Status</span><strong>${esc(audit.status)}</strong></div></div>`;mapping(audit);$("daRunAudit").disabled=audit.status==="mapping_required";setLinks();$("daApplyButton").disabled=false}
  function mapping(audit){const box=$("daMapping"),current=audit.column_mapping||{},fields={sotephwar_transection:["invoice_number","invoice_date","customer_name","product","quantity","total_amount","amount_received","note"],farm_transection:["invoice_number","invoice_date","customer_name","total_amount","amount_received","note"],transection:["invoice_date","transaction_type","category","sector","product","total_amount","payment_method","note"]}[audit.target_key];box.hidden=false;box.innerHTML=`<h2>AI Column Mapping</h2><p>Columns are matched by normalized header names, never position.</p><form id="daMappingForm">${fields.map(field=>`<div class="da-mapping-row"><strong>${esc(audit.headers[current[field]]??"Unmapped")}</strong><span>→</span><label>${esc(field)}<select name="${esc(field)}"><option value="">Ignore / unmapped</option>${audit.headers.map((header,index)=>`<option value="${index}" ${Number(current[field])===index?"selected":""}>${esc(header)}</option>`).join("")}</select></label></div>`).join("")}<label>Save as template (optional)<input name="template_name"></label><button class="button primary">Save mapping</button></form>`;$("daMappingForm").addEventListener("submit",saveMapping)}
  async function saveMapping(event){event.preventDefault();const data=new FormData(event.target),mapping={};for(const [key,value] of data.entries())if(key!=="template_name"&&value!=="")mapping[key]=Number(value);try{const body=await json(`/api/data-audit/${state.audit.id}/mapping`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({mapping,template_name:data.get("template_name")})});profile(body.audit);notice("Column mapping saved.")}catch(error){notice(error.message,true)}}
  $("daUploadForm").addEventListener("submit",async event=>{event.preventDefault();try{const body=await json("/api/data-audit/upload",{method:"POST",body:new FormData(event.target)});profile(body.audit);notice(`Audit #${body.audit.id} uploaded. Review the mapping, then run the read-only audit.`)}catch(error){notice(error.message,true)}});
  $("daRunAudit").addEventListener("click",async()=>{if(!state.audit)return;try{const body=await json(`/api/data-audit/${state.audit.id}/run`,{method:"POST"});profile(body.audit);renderKpis(body.audit.summary);notice("Read-only audit complete.");view("audit")}catch(error){notice(error.message,true)}});
  function renderKpis(summary={}){const values=[["Excel Rows",summary.excel_rows],["Database Rows",summary.database_rows],["Exact Matches",summary.exact_matches],["Alias Matches",summary.alias_matches],["Need Review",summary.need_review],["Duplicates",summary.duplicates],["Amount Mismatches",summary.amount_mismatches],["Quantity Mismatches",summary.quantity_mismatches],["Excel Only",summary.excel_only],["Database Only",summary.database_only]];$("daKpis").innerHTML=values.map(([label,value])=>`<article class="da-kpi"><span>${label}</span><strong>${Number(value||0).toLocaleString()}</strong></article>`).join("")}
  async function loadRows(){if(!state.audit)return;$("daRows").innerHTML='<tr><td colspan="8">Loading…</td></tr>';const query=new URLSearchParams({page:state.page,page_size:25,classification:state.classification,decision:state.decision,search:state.search,sort:state.sort,direction:state.direction});try{const body=await json(`/api/data-audit/${state.audit.id}/differences?${query}`);state.pages=body.pages;state.selected.clear();$("daRows").innerHTML=body.rows.map(row=>{const x=row.excel_values||{},d=row.database_values||{},voucher=x.invoice_number||d.invoice_number||"",date=x.invoice_date||d.invoice_date||"",customer=x.customer_name||d.customer_name||"",product=x.product||d.product||"";return `<tr><td><input type="checkbox" data-row-id="${row.id}"></td><td><strong>${esc(row.classification)}</strong><br><small>${esc(row.decision)}</small></td><td>${esc(voucher)}<br>${esc(date)}</td><td>${esc(customer)}<br>${esc(product)}</td><td class="da-values">${esc(JSON.stringify(x))}</td><td class="da-values">${esc(JSON.stringify(d))}</td><td class="da-values">${esc(JSON.stringify(row.differences||{}))}</td><td><div class="da-row-actions"><button data-detail='${esc(JSON.stringify(row))}'>View Details</button><button data-action="accept_excel" data-id="${row.id}">Accept Excel</button><button data-action="accept_database" data-id="${row.id}">Accept Database</button><button data-action="ignore" data-id="${row.id}">Ignore</button><button data-action="merge_alias" data-id="${row.id}">Merge Alias</button></div></td></tr>`}).join("")||'<tr><td colspan="8">No differences found.</td></tr>';$("daRows").querySelectorAll("[data-row-id]").forEach(input=>input.addEventListener("change",()=>input.checked?state.selected.add(Number(input.dataset.rowId)):state.selected.delete(Number(input.dataset.rowId))));$("daRows").querySelectorAll("[data-action]").forEach(button=>button.addEventListener("click",()=>saveDecision([Number(button.dataset.id)],button.dataset.action)));$("daRows").querySelectorAll("[data-detail]").forEach(button=>button.addEventListener("click",()=>{$("daDetailContent").textContent=JSON.stringify(JSON.parse(button.dataset.detail),null,2);$("daDetails").showModal()}));$("daPager").innerHTML=`<button class="button secondary" ${state.page<=1?"disabled":""} id="daPrev">Previous</button><span>Page ${state.page} of ${state.pages}</span><button class="button secondary" ${state.page>=state.pages?"disabled":""} id="daNext">Next</button>`;$("daPrev").onclick=()=>{state.page--;loadRows()};$("daNext").onclick=()=>{state.page++;loadRows()}}catch(error){notice(error.message,true)}}
  async function saveDecision(ids,decision){try{await json(`/api/data-audit/${state.audit.id}/decisions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({row_ids:ids,decision})});notice("Review decision saved.");loadRows()}catch(error){notice(error.message,true)}}
  document.querySelectorAll("#daTabs button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("#daTabs button").forEach(x=>x.classList.remove("active"));button.classList.add("active");state.classification=button.dataset.classification;state.page=1;loadRows()}));
  let searchTimer;$("daSearch").addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.search=$("daSearch").value.trim();state.page=1;loadRows()},250)});$("daDecisionFilter").addEventListener("change",()=>{state.decision=$("daDecisionFilter").value;state.page=1;loadRows()});
  $("daApplyButton").addEventListener("click",async()=>{if(!state.audit||!confirm("Apply every Accept Excel decision in one transaction?"))return;try{const body=await json(`/api/data-audit/${state.audit.id}/apply`,{method:"POST"});notice(`${body.changes_applied} approved changes applied.`);$("daChangeLog").hidden=false;profile(await (await json(`/api/data-audit/${state.audit.id}`)).audit)}catch(error){notice(error.message,true)}});
  function setLinks(){if(!state.audit)return;const base=`/api/data-audit/${state.audit.id}/export/`;$("daExportAll").href=base+"csv";$("daExportMismatch").href=base+"mismatch";$("daExportPdf").href=base+"pdf";$("daChangeLog").href=base+"changes"}
  async function loadHistory(){try{const body=await json("/api/data-audit/history");$("daHistoryRows").innerHTML=body.audits.map(a=>`<tr><td>#${a.id}</td><td>${esc(a.created_at)}</td><td>${esc(a.created_by)}</td><td>${esc(a.target_table)}</td><td>${esc(a.filename)}</td><td>${a.rows_compared}</td><td>${a.changes_applied}</td><td>${esc(a.status)}</td><td><button data-open="${a.id}">Open</button> <button data-delete="${a.id}">Delete</button></td></tr>`).join("")||'<tr><td colspan="9">No audits yet.</td></tr>';$("daHistoryRows").querySelectorAll("[data-open]").forEach(button=>button.addEventListener("click",async()=>{profile((await json(`/api/data-audit/${button.dataset.open}`)).audit);renderKpis(state.audit.summary);view("review")}));$("daHistoryRows").querySelectorAll("[data-delete]").forEach(button=>button.addEventListener("click",async()=>{if(!confirm(`Delete audit #${button.dataset.delete}?`))return;try{await json(`/api/data-audit/${button.dataset.delete}`,{method:"DELETE"});notice("Audit history deleted.");loadHistory()}catch(error){notice(error.message,true)}}))}catch(error){notice(error.message,true)}}
  async function loadAliases(type){try{const body=await json(`/api/data-audit/aliases?type=${type}`),editor=$(`da${type[0].toUpperCase()+type.slice(1)}AliasEditor`),list=$(`da${type[0].toUpperCase()+type.slice(1)}Aliases`);editor.innerHTML=`<form class="da-alias-form" data-alias-form><input type="hidden" name="alias_id"><input name="original_value" placeholder="Original value" required><input name="normalized_value" placeholder="Canonical value" required><button class="button primary">Save alias</button><button type="button" class="button secondary" data-alias-cancel hidden>Cancel</button></form>`;list.innerHTML=`<div class="da-alias-list">${body.aliases.map(a=>`<div class="da-alias-row"><span>${esc(a.original_value)}</span><span>→</span><strong>${esc(a.normalized_value)}</strong><small>${a.active?"Active":"Inactive"}</small><button type="button" class="button secondary" data-alias-edit="${a.id}">Edit</button></div>`).join("")||"No aliases saved."}</div>`;const formElement=editor.querySelector("form"),cancel=editor.querySelector("[data-alias-cancel]");const reset=()=>{formElement.reset();formElement.querySelector("button.primary").textContent="Save alias";cancel.hidden=true};cancel.onclick=reset;list.querySelectorAll("[data-alias-edit]").forEach(button=>button.onclick=()=>{const alias=body.aliases.find(item=>String(item.id)===button.dataset.aliasEdit);if(!alias)return;formElement.elements.alias_id.value=alias.id;formElement.elements.original_value.value=alias.original_value;formElement.elements.normalized_value.value=alias.normalized_value;formElement.querySelector("button.primary").textContent="Update alias";cancel.hidden=false;formElement.elements.original_value.focus()});formElement.addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.target),aliasId=form.get("alias_id"),payload={alias_type:type,original_value:form.get("original_value"),normalized_value:form.get("normalized_value")};try{await json(aliasId?`/api/data-audit/aliases/${aliasId}`:"/api/data-audit/aliases",{method:aliasId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});notice("Alias saved.");loadAliases(type)}catch(error){notice(error.message,true)}})}catch(error){notice(error.message,true)}}
  $("daExportVisible").addEventListener("click",()=>{if(state.audit)location.href=`/api/data-audit/${state.audit.id}/export/mismatch`});
  document.querySelectorAll(".da-sort").forEach(button=>button.addEventListener("click",()=>{if(state.sort===button.dataset.sort)state.direction=state.direction==="asc"?"desc":"asc";else{state.sort=button.dataset.sort;state.direction="asc"}state.page=1;loadRows()}));
})();
